version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672  # AMQP protocol (for your Python app)
      - 15672:15672  # RabbitMQ Management UI
    
    volumes:
      - data:/var/lib/rabbitmq


volumes:
  data:
